name: Regenerar Web
on:
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas

      - name: Analizar precios (solo gráficos)
        run: python analizar_precios_carrefour.py --solo-graficos

      - name: Generar web
        run: python generar_web_carrefour.py

      - name: Commit y push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ docs/
          git diff --staged --quiet || git commit -m "🌐 Web regenerada $(date +'%Y-%m-%d %H:%M')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
